### ISSUE TITLE
Provide GitHub Actions template for better use

### ISSUE THREAD

**Issue by go-zen-chu** [go-zen-chu/aictl#12]
## What is an issue?

- We do not provide github actions template yet. If we have, we can easily use it from GitHub Actions as shown below

```yaml
jobs:
  check-aictl:
    runs-on: ubuntu-latest
    steps:
    - uses: go-zen-chu/aictl@main
      with:
        query: "Hello! GitHub Action"
      env:
        AICTL_OPENAI_API_KEY: ${{ secrets.AICTL_OPENAI_API_KEY }}
```

## Goal of this issue

- [x] provide github actions template

## Proposal

- We already have action.yml so we can provide them via marketplace 

## Appendix

- Something you want to note
